### ISSUE TITLE
The default apache site isn't disabled

### ISSUE THREAD

**Issue by tedivm** [shoekstra/puppet-owncloud#14]
Because the default site isn't disabled the owncloud site does not appear without manual intervention.

**Comment by shoekstra** [comment]
Will need to test this, I didn't include it in the spec tests because of `default_vhost => false` in `apache.pp`.

What platform are you running it on?

**Comment by tedivm** [comment]
Ubuntu 14.04

**Comment by shoekstra** [comment]
I'm not able to replicate your issue unfortunately.

I've uploaded my vagrant boxes I use to test this (haven't been able to write proper acceptance tests yet), you can find it at [here](https://github.com/shoekstra/vagrant-puppet-owncloud).  Basically you want to check out that repo, `vagrant up ubuntu14` and when it's finished open `http://localhost:8443` in your browser.

I've also checked on the filesystem and see this inside the `000-default.conf`:

```
$ grep -v \# /etc/apache2/sites-enabled/000-default.conf
<VirtualHost *:80>

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html


        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
```

This doesn't contain anything that should prevent ownCloud working as expected.

If you're still able to get reproduce your problem using the Vagrant setup please let me know how I can do it, but as I cannot replicate it using a fresh install I'm putting this down as something local to your setup/system.

**Comment by jmnavarrol** [comment]
> I'm not able to replicate your issue unfortunately.

I do.

Looking at your comments I think I know what's happening: at least on Debian 7 (and I think on any other Debian too), document root for the default website is '/var/www' instead of '/var/www/html'.

Since owncloud package installs itself under '/var/www/owncloud' (which probably shouldn't, but that's an upstream/packager issue) the default site _"steps over"_ the owncloud one.  Deleting '/etc/apache2/sites-enabled/000-default.conf' does in fact publish owncloud (no wonder, since now it becomes the only active virtual site ).

**Comment by shoekstra** [comment]
What parameters are you using?

If `manage_apache` is true (default) then any non Puppet managed Apache configs will be removed, including the default site.  If `manage_apache` is set to false, then it's up to the user to fix conflicts like this.

Are you able to reproduce it using one of the [vagrant boxes](https://github.com/shoekstra/vagrant-puppet-owncloud)?

Until there I or someone writes beaker tests for this module I'm using those vagrant boxes for testing OS specific issues.  If it can't be reproduced using one of the vagrant boxes then it's not something I'm able to investigate further I'm afraid.

**Comment by jmnavarrol** [comment]
shoekstra dixit:
> What parameters are you using?

Defaults, basically (database gets created somewhere else):
```ruby
    class { 'owncloud':
        db_user       => $db_user,
        db_pass       => $db_password,
        datadirectory => $datadirectory,
    }
```

> If manage_apache is true (default) then any non Puppet managed Apache configs will be removed, including the default site.

Don't think so.  Using v0.4.2, that's what your apache.pp has to say:
```ruby
  if $::owncloud::manage_apache {
    class { '::apache':
      default_vhost => false,
      mpm_module    => 'prefork',
      purge_configs => false,
    }
    (...)
```
*purge_configs* is set to *false* by default and then *default_vhost* is set to *false*, yes, but since *purge_configs* is also _false_, this means the default config file, which gets created upon apache package installation, not puppet, won't be deleted.
