### ISSUE TITLE
url parameter don't modify config.php

### ISSUE THREAD

**Issue by clauded** [shoekstra/puppet-owncloud#15]
When an url parameter is specified (example url => 'myowncloud.mydomain.com'), the following error message is displayed on the web site : "You are accessing the server from an untrusted domain. Please contact your administrator".

The config.php file must be edited to allow the url:

'trusted_domains' => 
  array (
    0 => 'myowncloud.mydomain.com',
  ),

Either this file is managed with a template or a file_line statement could be used.

**Comment by shoekstra** [comment]
Hi!,

Thanks for the feedback.

Bit swamped with work at the moment but hope to clear the backlog of issues over the weekend and push a new release to the forge then.

**Comment by shoekstra** [comment]
From my testing it seems that while you've configured `myowncloud.mydomain.com` as the URL, you've accessed the ownCloud instance via another URL, and this other URL is then saved in the `trusted_domains` array.

When I tested with Vagrant, I set my domain to `owncloud.example.com` but I accessed the site by using `https://localhost:2201`.  When I looked in the `config.php` it contained:

```
  'trusted_domains' =>
  array (
    0 => 'localhost:2201',
  ),
```

Because at this time this module does not make the `config.php`, I can only suggest using the same URL to access the website as specified for the `$::owncloud::url` parameter.  Alternatively you will need to amend the `config.php` by hand to update the `trusted_domain` value.

Sorry for the inconvenience but unfortunately this is something not easily fixed by this module at this time.
