### ISSUE TITLE
No support for Debian

### ISSUE THREAD

**Issue by rdoering** [shoekstra/puppet-owncloud#19]
These files are describing an support for ubuntu only.

modules/owncloud/manifests/install.pp
modules/owncloud/manifests/params.pp

**Comment by shoekstra** [comment]
There is Debian support, see the following:

* https://github.com/shoekstra/puppet-owncloud/blob/develop/manifests/install.pp#L8-L9
* https://github.com/shoekstra/puppet-owncloud/blob/develop/manifests/params.pp#L7-L8

**Comment by jmnavarrol** [comment]
shoekstra said:
> There is Debian support

No, there isn't (well, kindof): the preferred method to install a puppet module is using the Puppet Forge.  Current published version at the Forge is 0.4.1 from Jul 19th 2015 which, despite its claim of supporting Debian, it explicitly doesn't (see published params.pp file).

**Comment by shoekstra** [comment]
@jmnavarrol, I've just downloaded and extracted latest version from the forge and it does contain references to Debian osfamily and operatingsystem.

**Comment by jmnavarrol** [comment]
@shoekstra: found two things:
1) It was partly my problem because I oversaw which version of your module `puppet module install` was downloading: it was v0.1.1 instead of the latest one!!! (I was under the impression that 'puppet module install' would try to update dependencies as needed or, at least, warn that it couldn't install the latest version.  Unfortunately, that's not the case).
2) Digging on why it was downloading such an old version, first I thought it was because some modules yours one depends on were not at their latest version on my modules tree, so I upgraded them.

Upgrading dependencies didn't work, so I took a more extreme approach: I tried to install your module (from the forge) into an empty directory: `puppet module install shoekstra/owncloud -i new-dir/`.  This would install a newer version of your module (and its declared dependencies) but still not the latest one: it installs v0.4.0 instead of v0.4.2.

I don't know 'puppet module' internals good enough to know exactly what's happening but I can say your metadata.json file states "stahnma/epel","version_requirement":">= 1.0.0 <= 1.0.2" while latest version for that module is 1.2.2, so I would suggest two approaches (and a third one for myself):
1) Update stahnma/epel's dependency to cover 1.2.2 (and see if your module still works as expected).
2) Review your metadata.json so only first-level dependencies are declared, i.e.: you declare dependencies on both puppetlabs/apache and puppetlabs/stdlib, but puppetlabs/apache already depends on puppetlabs/stdlib by itself, so it seems both to be redundant and an added difficulty for you to track dependencies without end up with problems like this one.
3) On my side, I'll try to put some time into puppet module's dependency management, since it seems something is not working as well as it should: given that I'm using Debian, dependency management probably shouldn't consider versions for modules that aren't targeted for my operating system.  Maybe I'll create a feature request for that at Puppetlabs.

**Comment by jmnavarrol** [comment]
Hey, now I see you already were aware of this! see #18.

**Comment by shoekstra** [comment]
Interesting!  Admittedly I don't use puppet as much since I moved companies so I don't keep on top of dependency versions as much as I used to. I am trying to get back into it and will be giving this module more attention.

Responding to your comments:

1. I tend to pin the max version allowed to the current module at the time of publishing (but did not this time, completely slipped my mind), as I've had bad experiences in the past.  While I want to rely on semver, I've had modules break because people make breaking changes in a minor release, so the max version will remain but I will always try to review/merge PRs related to dependency versions as quick as possible as I know this can be frustrating.

2. That's because I use helpers from stdlib, so I need to ensure my module works with the specified version.

3. That would be helpful, as mentioned in 1) I will try to review/merge PRs related to dependency versions ASAP.

Trying to get beaker tests working and then hopefully testing will be a lot easier for different distributions.  Will need to see how to incorporate testing the correct module version.
